[package]
name = "clvm_tools_rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
num-bigint = "0.4.0"
bls12_381 = "0.5.0"
bytestream = "0.4.1"
num-traits = "0.2.14"
lazy_static = "1.4.0"
unicode-segmentation = "1.8.0"
derivative = "2.2.0"
encoding8 = "0.3.2"
num = "0.4.0"
indoc = "1.0"
do-notation = "0.1.3"
serde_json = "1.0"
sha2 = "0.9.5"
yamlette = "0.0.8"

[dependencies.clvm_rust]
git = "https://github.com/prozacchiwawa/clvm_rs"
branch = "20211029-try-config"

[build-dependencies]
pyo3-build-config = "0.14.5"

[lib]
name = "clvm_tools_rs"
crate-type = ["cdylib", "rlib"]

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[target.'cfg(target_family="wasm")'.dependencies]
wasm-bindgen = "0.2.75"
wasm-bindgen-test = "0.3.25"

[target.'cfg(not(target_family="wasm"))'.dependencies.pyo3]
version = "0.14.2"
features = ["abi3-py37"]

[[bin]]
name = "opd"
path = "src/classic/bins/opd.rs"

[[bin]]
name = "opc"
path = "src/classic/bins/opc.rs"

[[bin]]
name = "run"
path = "src/classic/bins/run.rs"

[[bin]]
name = "brun"
path = "src/classic/bins/brun.rs"

[[bin]]
name = "cldb"
path = "src/classic/bins/cldb.rs"
